logo="""
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                bbbbbbbb                                                    
        GGGGGGGGGGGGG                                                                                      tttt         hhhhhhh                                                                                                 b::::::b                                                    
     GGG::::::::::::G                                                                                   ttt:::t         h:::::h                                                                                                 b::::::b                                                    
   GG:::::::::::::::G                                                                                   t:::::t         h:::::h                                                                                                 b::::::b                                                    
  G:::::GGGGGGGG::::G                                                                                   t:::::t         h:::::h                                                                                                  b:::::b                                                    
 G:::::G       GGGGGGuuuuuu    uuuuuu      eeeeeeeeeeee        ssssssssss       ssssssssss        ttttttt:::::ttttttt    h::::h hhhhh           eeeeeeeeeeee         nnnn  nnnnnnnn    uuuuuu    uuuuuu     mmmmmmm    mmmmmmm   b:::::bbbbbbbbb        eeeeeeeeeeee    rrrrr   rrrrrrrrr   
G:::::G              u::::u    u::::u    ee::::::::::::ee    ss::::::::::s    ss::::::::::s       t:::::::::::::::::t    h::::hh:::::hhh      ee::::::::::::ee       n:::nn::::::::nn  u::::u    u::::u   mm:::::::m  m:::::::mm b::::::::::::::bb    ee::::::::::::ee  r::::rrr:::::::::r  
G:::::G              u::::u    u::::u   e::::::eeeee:::::eess:::::::::::::s ss:::::::::::::s      t:::::::::::::::::t    h::::::::::::::hh   e::::::eeeee:::::ee     n::::::::::::::nn u::::u    u::::u  m::::::::::mm::::::::::mb::::::::::::::::b  e::::::eeeee:::::eer:::::::::::::::::r 
G:::::G    GGGGGGGGGGu::::u    u::::u  e::::::e     e:::::es::::::ssss:::::ss::::::ssss:::::s     tttttt:::::::tttttt    h:::::::hhh::::::h e::::::e     e:::::e     nn:::::::::::::::nu::::u    u::::u  m::::::::::::::::::::::mb:::::bbbbb:::::::be::::::e     e:::::err::::::rrrrr::::::r
G:::::G    G::::::::Gu::::u    u::::u  e:::::::eeeee::::::e s:::::s  ssssss  s:::::s  ssssss            t:::::t          h::::::h   h::::::he:::::::eeeee::::::e       n:::::nnnn:::::nu::::u    u::::u  m:::::mmm::::::mmm:::::mb:::::b    b::::::be:::::::eeeee::::::e r:::::r     r:::::r
G:::::G    GGGGG::::Gu::::u    u::::u  e:::::::::::::::::e    s::::::s         s::::::s                 t:::::t          h:::::h     h:::::he:::::::::::::::::e        n::::n    n::::nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::::::::::::e  r:::::r     rrrrrrr
G:::::G        G::::Gu::::u    u::::u  e::::::eeeeeeeeeee        s::::::s         s::::::s              t:::::t          h:::::h     h:::::he::::::eeeeeeeeeee         n::::n    n::::nu::::u    u::::u  m::::m   m::::m   m::::mb:::::b     b:::::be::::::eeeeeeeeeee   r:::::r            
 G:::::G       G::::Gu:::::uuuu:::::u  e:::::::e           ssssss   s:::::s ssssss   s:::::s            t:::::t    tttttth:::::h     h:::::he:::::::e                  n::::n    n::::nu:::::uuuu:::::u  m::::m   m::::m   m::::mb:::::b     b:::::be:::::::e            r:::::r            
  G:::::GGGGGGGG::::Gu:::::::::::::::uue::::::::e          s:::::ssss::::::ss:::::ssss::::::s           t::::::tttt:::::th:::::h     h:::::he::::::::e                 n::::n    n::::nu:::::::::::::::uum::::m   m::::m   m::::mb:::::bbbbbb::::::be::::::::e           r:::::r            
   GG:::::::::::::::G u:::::::::::::::u e::::::::eeeeeeee  s::::::::::::::s s::::::::::::::s            tt::::::::::::::th:::::h     h:::::h e::::::::eeeeeeee         n::::n    n::::n u:::::::::::::::um::::m   m::::m   m::::mb::::::::::::::::b  e::::::::eeeeeeee   r:::::r            
     GGG::::::GGG:::G  uu::::::::uu:::u  ee:::::::::::::e   s:::::::::::ss   s:::::::::::ss               tt:::::::::::tth:::::h     h:::::h  ee:::::::::::::e         n::::n    n::::n  uu::::::::uu:::um::::m   m::::m   m::::mb:::::::::::::::b    ee:::::::::::::e   r:::::r            
        GGGGGG   GGGG    uuuuuuuu  uuuu    eeeeeeeeeeeeee    sssssssssss      sssssssssss                   ttttttttttt  hhhhhhh     hhhhhhh    eeeeeeeeeeeeee         nnnnnn    nnnnnn    uuuuuuuu  uuuummmmmm   mmmmmm   mmmmmmbbbbbbbbbbbbbbbb       eeeeeeeeeeeeee   rrrrrrr            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
"""
